---

name: haskell fibonacci

# yamllint disable-line rule:truthy
on:
  push:
    branches: ['master', 'feature*']
    tags-ignore: ['*']
  check_run:
    types: [rerequested, requested_action]
# yamllint enable

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            .stack/
            .stack-work/
          key: $GITHUB_REF

      - name: setup
        run: |
          stack update
          stack setup
          stack path
          stack query
          stack ls dependencies
          cabal check

      - name: build
        run: stack build --pedantic --no-test

      - name: test
        run: stack test

      - name: exec
        run: |
          echo fib -h
          stack exec fib -- -h
          echo fib -i 5
          stack exec fib -- -i 5
          echo fib -s 5
          stack exec fib -- -s 5

      - name: benchmark
        run: stack bench --ba '-o .stack-work/benchmark.html'

      - name: document
        if: github.ref == 'refs/heads/master'
        run: |
          stack test --coverage
          stack haddock --fast

      - name: copy
        if: github.ref == 'refs/heads/master'
        run: |
          mv $(stack path --local-doc-root) public/
          mv $(stack path --local-hpc-root) public/
          mv .stack-work/benchmark.html public/

      - name: publish
        if: success() && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
