---

name: haskell fibonacci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      CABAL_CONFIG: $GITHUB_WORKSPACE/.cabal/config
      RTSOPTS: +RTS -N1

    steps:

      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            cabal.project.local
            .cabal/config
            dist/
            dist-newstyle/
            .stack/
            .stack-work/
          key: $GITHUB_REF

      - name: setup
        run: |
          mkdir -p .cabal/
          cabal user-config update
          cabal new-update --only-dependencies

      - name: build
        run: cabal new-build

      - name: test
        run: cabal new-test --test-show-details=always

      - name: exec
        run: |
          echo fib -h
          cabal exec -- fib -h   $RTSOPTS
          echo fib -i 5
          cabal exec -- fib -i 5 $RTSOPTS -s
          echo fib -s 5
          cabal exec -- fib -s 5 $RTSOPTS -s

      - name: documentation
        if: success() && github.ref == 'refs/heads/main'
        run: cabal new-haddock --haddock-all --haddock-quickjump --haddock-hyperlink-source

      - name: copy
        if: success() && github.ref == 'refs/heads/main'
        run: |
          mkdir -p public/
          cp -pr dist-newstyle/build/x86_64-linux/ghc*/Fibonacci*/doc/html/Fibonacci/* public/

      - name: publish
        uses: crazy-max/ghaction-github-pages@v0.4.0
        if: success() && github.ref == 'refs/heads/main'
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
